// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiHSuyWiHG_6BvRKtJmwBu3SBLaIsKmfk',
    appId: '1:698816170759:web:1e54488be6ae5d6df793a2',
    messagingSenderId: '698816170759',
    projectId: 'smartmedicinedispenser',
    authDomain: 'smartmedicinedispenser.firebaseapp.com',
    storageBucket: 'smartmedicinedispenser.firebasestorage.app',
    measurementId: 'G-F45X84DMDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMAN4gGScHl6lEbIPC0VzFxA_uszTkm1Y',
    appId: '1:698816170759:android:61553268b8c02eccf793a2',
    messagingSenderId: '698816170759',
    projectId: 'smartmedicinedispenser',
    storageBucket: 'smartmedicinedispenser.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0vhiUqyDSG1uNhh9K9xrWeUnA3Sc3AU',
    appId: '1:698816170759:ios:466465f1adb6c343f793a2',
    messagingSenderId: '698816170759',
    projectId: 'smartmedicinedispenser',
    storageBucket: 'smartmedicinedispenser.firebasestorage.app',
    iosBundleId: 'com.example.dispenserapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi0vhiUqyDSG1uNhh9K9xrWeUnA3Sc3AU',
    appId: '1:698816170759:ios:466465f1adb6c343f793a2',
    messagingSenderId: '698816170759',
    projectId: 'smartmedicinedispenser',
    storageBucket: 'smartmedicinedispenser.firebasestorage.app',
    iosBundleId: 'com.example.dispenserapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiHSuyWiHG_6BvRKtJmwBu3SBLaIsKmfk',
    appId: '1:698816170759:web:a10a2083909f0e8df793a2',
    messagingSenderId: '698816170759',
    projectId: 'smartmedicinedispenser',
    authDomain: 'smartmedicinedispenser.firebaseapp.com',
    storageBucket: 'smartmedicinedispenser.firebasestorage.app',
    measurementId: 'G-987NKFTXVL',
  );
}
